export const FETCH_IMAGES = 'FETCH_IMAGES';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAIL = 'FETCH_IMAGES_FAIL';
export const FETCH_MORE_IMAGES = 'FETCH_MORE_IMAGES';
export const FETCH_MORE_IMAGES_SUCCESS = 'FETCH_MORE_IMAGES_SUCCESS';
export const FETCH_MORE_IMAGES_FAIL = 'FETCH_MORE_IMAGES_FAIL';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';